spring.application.name=HeladosFulSta
spring.datasource.url=jdbc:postgresql://localhost:5432/HeladosFulsta
spring.datasource.username=user_java
server.port=8095
spring.datasource.password=1234
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
